#+TITLE: qp-arduino README
#+AUTHOR: Peter Polidoro
#+EMAIL: peter@polidoro.io

* Documentation

https://janelia-arduino.github.io/qp-arduino

* Repository Information
- Name: qp-arduino
- Description: QP real-time embedded framework for Arduino
- Version: 6.9.5
- qpcpp version: 6.9.4
- qm version: 5.1.3
- Release Date: 2024-10-29
- Creation Date: 2017-01-30
- License: GPLv3
- Forked From Repository: https://github.com/QuantumLeaps/qp-arduino
- URL: https://github.com/janelia-arduino/qp-arduino
- Author: Quantum Leaps
- Fork Maintainer: Peter Polidorop
- Email: peter@polidoro.io
- Copyright: Quantum Leaps, LLC
- References:
  - https://www.state-machine.com/arduino

* Description

The Quantum Leaps’ QP™ real-time embedded frameworks (RTEFs) and the QM™
modeling tool complement the Arduino platform and provide everything you need to
program Arduino graphically with event-driven active objects and modern
hierarchical state machines.

* Development

** PlatformIO

PlatformIO can be used as an alternative to the Arduino IDE for compiling and
uploading Arduino code to embedded boards using a command line interface.

*** Install PlatformIO Core

[[https://docs.platformio.org/en/latest/core/installation/index.html]]

#+BEGIN_SRC sh
python3 -m venv .venv
source .venv/bin/activate
pip install platformio
pio --version
#+END_SRC

*** 99-platformio-udev.rules

Linux users have to install udev rules for PlatformIO supported boards/devices.

**** Download udev rules file to /etc/udev/rules.d

#+BEGIN_SRC sh
curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules | sudo tee /etc/udev/rules.d/99-platformio-udev.rules
#+END_SRC

**** Restart udev management tool

#+BEGIN_SRC sh
sudo service udev restart
#+END_SRC

**** Add user to groups

#+BEGIN_SRC sh
sudo usermod -a -G dialout $USER && sudo usermod -a -G plugdev $USER
#+END_SRC

**** Remove modemmanager

#+BEGIN_SRC sh
sudo apt-get purge --auto-remove modemmanager
#+END_SRC

**** After setting up rules and groups

You will need to log out and log back in again (or reboot) for the user group changes to take effect.

After this file is installed, physically unplug and reconnect your board.

*** Compile the firmware

**** Gnu/Linux

#+BEGIN_SRC sh
make teensy-firmware
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio run -e teensy41
#+END_SRC

*** Upload the firmware

**** Gnu/Linux

#+BEGIN_SRC sh
make teensy-upload
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio run -e teensy41 -t upload
#+END_SRC

*** Serial Terminal Monitor

**** Gnu/Linux

#+BEGIN_SRC sh
make monitor
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio device monitor
#+END_SRC


** QP

*** QM Graphical Modeling and Code Generation Tool

**** Download and Install

#+BEGIN_SRC shnn
cd ~ && rm -rf qp && mkdir qp && cd qp
curl -OL https://github.com/QuantumLeaps/qm/releases/download/v5.1.3/qm_5.1.3-linux64.zip
unzip qm_5.1.3-linux64.zip && rm qm_5.1.3-linux64.zip && mv qm qm-5.1.3
chmod u+x qm-5.1.3/bin/qm && chmod u+x qm-5.1.3/bin/qm.sh
alias qm='~/qp/qm-5.1.3/bin/qm.sh'
#+END_SRC

*** Qtools

**** Download and Install

#+BEGIN_SRC shnn
cd ~/qp
curl -OL https://github.com/QuantumLeaps/qtools/releases/download/v6.9.3/qtools-posix_6.9.3.zip
unzip qtools-posix_6.9.3.zip && rm qtools-posix_6.9.3.zip && mv qtools qtools-6.9.3
cd qtools-6.9.3/qspy/posix
make
alias qspy='~/qp/qtools-6.9.3/bin/qspy'
#+END_SRC

